import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/app/ui/Header'
import Footer from '@/app/ui/Footer'
import './home.module.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Git | Peter  Kudeláš',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body className={`${inter.className} container`}>
        <Header />
        <main>

        {children}
        </main>
        <Footer />
        </body>
    </html>
  )
}
